#!/usr/bin/env bash


liste_des_utilisateur():
    echo "liste des utilisateur "
    cut -d: -f1 /etc/passwd
    echo ""
    echo "pour retournéee au menu "gestion des utilisateur " entée 1 "
    read choix 
     if [ "$choix" -eq 1 ]; then 
        source users-menu.sh
    else
        echo "Choix invalide. Retour au menu principal..."
        source host-manager.sh
    fi

add_un_utilisateur():
    # ont prévient que l'utilisateur doit passe en root avec un sudo 
    #echo "pour ajoute un utilisateur il faudra passer en root en utilisant la commande sudo " 

    read -p "Entrez le noms d'utilisateur : " USERNAME
    # ont verifie si le noms d'utilisateur est disponible/existe deja 
    if id "$USERNAME" &> /dev/null ; then
            echo " l'utilisateur $USERNAME exit deja " 
    fi


    # ont demande le mots de passe a l'utilisateur
    read -s -p " Entrez le mots de passe pour $USERNAME :" Passwd
    echo " "

    #ont demande le goupe principal
    read -p " Veulliez entrez le groupe principale pour l'utilisateur $USERNAME :" Groupe

    if ! getent group "$Groupe" &>/dev/null; then
        echo "Le groupe '$Groupe' n'existe pas. Voulez-vous le créer ? (YES/NO)"
        read choix
        if [ "$choix" == "YES" ]; then
            groupadd "$Groupe"
            echo "Groupe '$Groupe' créé avec succès."
        else 
            echo "Annulation de l'ajout de l'utilisateur."
            source users-menu.sh
        fi
    fi

    useradd -m -g "$Groupe" "$USERNAME"

    # Ajouter le mot de passe à l'utilisateur
    echo "$USERNAME:$Passwd" | chpasswd

    echo "Utilisateur '$USERNAME' ajouté avec succès au groupe '$Groupe'."


    echo "pour retournéee au menu "gestion des utilisateur " entée "1" "
    read choix 
     if [ "$choix" -eq 1 ]; then
        source users-menu.sh
    else
        echo "Choix invalide. Retour au menu principal..."
        source host-manager.sh
    fi

modif_sur_utilisateur():
    echo "modifi les infos d'un utilisateur" 

    







    echo "pour retournéee au menu "gestion des utilisateur " entée "1" "
    read choix 
     if [ "$choix" -eq 1 ]; then
        source users-menu.sh
    else
        echo "Choix invalide. Retour au menu principal..."
        source host-manager.sh
    fi

#ont doit pouvoir modifier tout les infos d'un utilisteur nom, MDP, groupe
















all_save_personnal_user( ):
    echo " permet de sauvgardé complétement des dossier de tout les utilisateur "

#doit save tout les dossier de tout les utilisateur vers un lieu de stokage externe ont pourra stocker ca dans /mnt/export