#!/usr/bin/env bash


liste_des_utilisateur(){
    echo "liste des utilisateur "
    cut -d: -f1 /etc/passwd
    echo ""
    echo "pour retournéee au menu "gestion des utilisateur " entée 1 "
    read choix 
    if [ "$choix" -eq 1 ]; then 
        source users-menu.sh
    else
        echo "Choix invalide. Retour au menu principal..."
        source host-manager.sh
    fi
}   
add_un_utilisateur(){
    # ont prévient que l'utilisateur doit passe en root avec un sudo 
    #echo "pour ajoute un utilisateur il faudra passer en root en utilisant la commande sudo " 

    read -p "Entrez le noms d'utilisateur : " USERNAME
    # ont verifie si le noms d'utilisateur est disponible/existe deja 
    if id "$USERNAME" &> /dev/null ; then
            echo " l'utilisateur $USERNAME exit deja " 
    fi


    # ont demande le mots de passe a l'utilisateur
    read -s -p " Entrez le mots de passe pour $USERNAME :" Passwd
    echo " "

    #ont demande le goupe principal
    read -p " Veulliez entrez le groupe principale pour l'utilisateur $USERNAME :" Groupe

    if ! getent group "$Groupe" &>/dev/null; then
        echo "Le groupe '$Groupe' n'existe pas. Voulez-vous le créer ? (YES/NO)"
        read choix
        if [ "$choix" == "YES" ]; then
            groupadd "$Groupe"
            echo "Groupe '$Groupe' créé avec succès."
        else 
            echo "Annulation de l'ajout de l'utilisateur."
            source users-menu.sh
        fi
    fi

    useradd -m -g "$Groupe" "$USERNAME"

    # Ajouter le mot de passe à l'utilisateur
    echo "$USERNAME:$Passwd" | chpasswd

    echo "Utilisateur '$USERNAME' ajouté avec succès au groupe '$Groupe'."


    echo "pour retournéee au menu "gestion des utilisateur " entée "1" "
    read choix 
    if [ "$choix" -eq 1 ]; then
        source users-menu.sh
    else
        echo "Choix invalide. Retour au menu principal..."
        source host-manager.sh
    fi
}




modif_username(){
    read -p "Entrez le nom de l'utilisateur à modifier : " Username

    # ont vérifie si l'utilisateur existe et si il existe pas ont renvoie au menu utilisateur 
    if ! id "$Username" &>/dev/null; then
        echo "L'utilisateur '$Username' n'existe pas."
        source sous_menu_modif_utilisateur
    else 
        read -p "Entrez le nouveau nom de l'utilisateur : " New_Username
            usermod -l "$New_Username" "$Username"
            echo "Le nom de l'utilisateur a été changé en '$New_Username'."
    fi
}

modif_passwd(){
    read -p "Entrez le nom de l'utilisateur à modifier : " Username

    # ont vérifie si l'utilisateur existe et si il existe pas ont renvoie au menu utilisateur 
    if ! id "$Username" &>/dev/null; then
        echo "L'utilisateur '$Username' n'existe pas."
        source sous_menu_modif_utilisateur
    else
        read -s -p "Entrez le nouveau mot de passe : " News_Passwd
        echo ""
        echo "$Username:$News_Passwd" | chpasswd
        echo "Le mot de passe de l'utilisateur '$Username' a été changé."
        source sous_menu_modif_utilisateur
    fi      
           } 
modif_groupe_principal(){
    echo "modifie le groupe principale d'un utilisateur" 

    read -p "Entrez le nom de l'utilisateur à modifier : " Username

    # ont vérifie si l'utilisateur existe et si il existe pas ont renvoie au menu utilisateur 
    if ! id "$Username" &>/dev/null; then
        echo "L'utilisateur '$Username' n'existe pas."
        source sous_menu_modif_utilisateur
    else
        read -p "Entrez le nouveau groupe principal : " New_groupe
        if ! getent group "$New_groupe" &>/dev/null; then
            echo "Le groupe '$New_groupe' n'existe pas. Voulez-vous le créer ? (YES/NO)"
            read choix
            if [ "$choix" == "YES" ]; then
                groupadd "$New_groupe"
                echo "Groupe '$New_groupe' a bien etait crée ."
                usermod -g "$New_groupe" "$Username"
                echo "Le groupe principal de l'utilisateur '$Username' a été changé en '$New_groupe'."
            else 
                echo "Annulation de l'ajout de l'utilisateur."
                source sous_menu_modif_utilisateur
            fi
        fi
    fi
}









all_save_personnal_user( ){
    echo " permet de sauvgardé complétement des dossier de tout les utilisateur "

#doit save tout les dossier de tout les utilisateur vers un lieu de stokage externe ont pourra stocker ca dans /mnt/export
}