#!/usr/bin/env bash

function sous_menu_modif_utilisateur() {
  clear 
  echo "                                                     "
  echo "   modifier un utilisateur                           "
  echo "                                                     "      
  echo "  1.modifier le noms d'un utilisateur                "
  echo "                                                     " 
  echo "  2.modifier le mots de passe  d'un utilisateur      "
  echo "                                                     "
  echo "  3.modifier le groupe d'un utilisateur              "
  echo "                                                     "
  echo "  4.Quitter le Menu                                  "
  echo "                                                     "
  echo -n "veulliez choisir une options : "
}

while true; do
  sous_menu_modif_utilisateur
  read -r choix

  case "$choix" in

  1)
    echo "Vous avez choisi de modifier le noms d'un utilisateur"
    source modif_username()
    exit 0
    ;;

  2)
    echo "Vous avez choisi modifier le mots de passe  d'un utilisateur"
    source modif_passwd()
    exit 0
    ;;
  3)
    echo "Vous avez choisi modifier le groupe principal d'un utilisateur"
    source modif_groupe_principal()
    exit 0
    ;;
  4)
    echo "Vous avez choisi de Quitter le Menu "
    source user-menu.sh
    exit 0
    ;;
  
  *)
    echo " options invalide , veulliez réessayer."
    exit 0
    ;;
  esac
done